POST http://localhost:8080/institution
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "email": "fct@fct",
  "id": 0,
  "name": "FCT",
  "phoneNumb": "2222",
  "reviewers": [],
  "students": []
}

###
POST http://localhost:8080/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
"id": 0,
  "role": "STUDENT"
}

###
POST http://localhost:8080/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "role": "REVIEWER"
}

###
POST http://localhost:8080/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "role": "ADMIN"
}

###
POST http://localhost:8080/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "role": "SPONSOR"
}

###
POST http://localhost:8080/institution
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "email": "ist@ist",
  "id": 0,
  "name": "IST",
  "phoneNumb": "11111",
  "reviewers": [],
  "students": []
}

###
POST http://localhost:8080/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "address": "RUA",
  "applications": [
  ],
  "birthDate": "2020-10-17",
  "course": "MIEI",
  "cvId": 0,
  "email": "jmpss",
  "id": 0,
  "institutionId": 1,
  "name": "JOAO MIGUEsL",
  "password": "a",
  "roles": ["ADMIN", "STUDENT"],
  "username": "Luis"
}

###
POST http://localhost:8080/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
"address": "RUA",
"applications": [
],
"birthDate": "2020-10-17",
"course": "MIEI",
"cvId": 0,
"email": "ola",
"id": 0,
"institutionId": 1,
"name": "JOAO MIGUEsL",
"password": "a",
"roles": ["ADMIN"],
"username": "ola"
}


###
POST http://localhost:8080/student
Content-Type: application/json
Authorization: Basic Luis a

{
  "address": "RUA",
  "applications": [
  ],
  "birthDate": "2020-10-17",
  "course": "MIEI",
  "cvId": 0,
  "email": "hGg",
  "id": 0,
  "institutionId": 1,
  "name": "Hugo",
  "password": "as",
  "username": "ass",
  "roles": ["STUDENT"]
}

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "address": "RUA",
  "applications": [
  ],
  "birthDate": "2020-10-17",
  "course": "MIEI",
  "cvId": 0,
  "email": "lulu",
  "id": 1,
  "institutionId": 1,
  "name": "Luis"
}

###
POST http://localhost:8080/sponsor
Content-Type: application/json
Authorization: Basic Luis a

{
  "email": "emal@pt",
  "name": "MANEL O PRATOCIONADOR",
  "phoneNumber": "9999",
  "sponsorID": 0,
  "password": "gg",
  "username": "bfff",
  "roles": ["SPONSOR"]
}

###
POST http://localhost:8080/grant
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "applicationQuestions": [
    {
      "fieldDescription": "string",
      "mandatory": true,
      "type": "string"
    }
  ],
  "applications": [
  ],
  "deadline": "2020-10-18",
  "description": "string",
  "funding": 100000,
  "grantId": 1,
  "openingDate": "2020-10-17",
  "sponsorId": 4,
  "title": "OLA"
}

###
POST http://localhost:8080/application
Content-Type: application/json
Authorization: Basic ass as

{
  "applicationID": 0,
  "grantID": 1,
  "responses": [
    {
      "response": "string"
    }
  ],
  "status": "string",
  "studentID": 3,
  "submissionDate": "2020-10-17",
  "reviews": []
}


###
POST http://localhost:8080/reviewer
Content-Type: application/json
Authorization: Basic Luis a

{
  "address": "ruaa",
  "birthDate": "2020-10-26",
  "email": "rev1@rev",
  "evals": [],
  "id": 0,
  "institutionID": 1,
  "name": "EVAL1",
  "username": "f",
  "password": "l",
  "roles": ["REVIEWER"]
}

###
POST http://localhost:8080/reviewer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "address": "ruaa",
  "birthDate": "2020-10-26",
  "email": "rev2@rev",
  "evals": [],
  "id": 0,
  "institutionID": 1,
  "name": "EVAL2",
  "username": "v",
  "password": "l",
  "roles": ["REVIEWER"]
}

###
POST http://localhost:8080/panel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM


{
  "grant": 1,
  "panelChair": 5,
  "panelID": 0,
  "reviewer": [
    5
  ]
}

###
POST http://localhost:8080/student/1/CV
Content-Type: application/json

{
  "fields": [
    {
      "content": "MIEI",
      "mandatory": true,
      "type": "CURSO"
    }
  ],
  "id": 0
}

###
PUT http://localhost:8080/student
Content-Type: application/json

{
  "address": "RUA",
  "applications": [
  ],
  "birthDate": "2020-10-18",
  "course": "MIEQB",
  "cvId": 0,
  "email": "jmpola",
  "id": 1,
  "institutionId": 2,
  "name": "JOAO MIGUEL"
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "applicationId": 1,
  "grantId": 1,
  "id": 0,
  "revId": 5,
  "status": 2
}
###
POST http://localhost:8080/student/2/CV
Content-Type: application/json
Authorization: Basic ass as

{
  "fields": [
    {
      "content": "string",
      "mandatory": true,
      "type": "string"
    }
  ],
  "id": 0
}