POST http://localhost:8080/panel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImV4cCI6MTYwNzQ4MzMzOCwiaWF0IjoxNjA3NDQ3MzM4LCJ1c2VybmFtZSI6ImEifQ.nkWaxjWk2E0Mr-Mt4lm6KVvdaFwhKFdpO3T1ahyUJF8

{
  "panelID": 0,
  "panelChair": 16,
  "reviewer": [5,6,16,17],
  "grant": 1
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": true,
  "revId": 8,
  "applicationId": 1,
  "grantId": 1,
  "textField": "Então se és bom, siga nisso!"
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": true,
  "revId": 10,
  "applicationId": 1,
  "grantId": 1,
  "textField": "Vamos ver se és assim tão bom."
}

###
POST http://localhost:8080/panel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "panelID": 0,
  "panelChair": 8,
  "reviewer": [8,11,9,12],
  "grant": 2
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": false,
  "revId": 8,
  "applicationId": 4,
  "grantId": 2,
  "textField": "É necessário ter pelo menos umas bases na area..."
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfUkVWSUVXRVIifV0sImV4cCI6MTYwODAwNDIzOCwiaWF0IjoxNjA3OTY4MjM4LCJ1c2VybmFtZSI6ImxlZ2F0aGVhdXguam9zZSJ9.L3YAsqXnoOd2BeDjEyH6gXWG0Avd_ZekV_EPrKWnhv8

{
  "id": 0,
  "status": false,
  "revId": 16,
  "applicationId": 11,
  "grantId": 3,
  "textField": "Se não sabes nada não entras!"
}

###
POST http://localhost:8080/panel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3NTcwMTA4LCJpYXQiOjE2MDc1MzQxMDgsInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.6zzoY0xyRQ5GqEIf-JojCci9u3nIL4GfiuxkHYpQh2w

{
  "panelID": 0,
  "panelChair": 10,
  "reviewer": [10,16,8,9],
  "grant": 3
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": false,
  "revId": 8,
  "applicationId": 5,
  "grantId": 3,
  "textField": "Se não jogas vais te aborrecer..."
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": false,
  "revId": 11,
  "applicationId": 5,
  "grantId": 3,
  "textField": "Sem jogar não há trabalhar."
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": true,
  "revId": 8,
  "applicationId": 6,
  "grantId": 3,
  "textField": "Muita experiencia na area é importante, ainda bem que tens muita!"
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": true,
  "revId": 11,
  "applicationId": 6,
  "grantId": 3,
  "textField": "O candidato demonstra uma grande experiencia em diversas plataformas."
}

###
POST http://localhost:8080/panel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "panelID": 0,
  "panelChair": 10,
  "reviewer": [10,13,9,11],
  "grant": 4
}

###
POST http://localhost:8080/panel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "panelID": 0,
  "panelChair": 8,
  "reviewer": [13,8,6,7],
  "grant": 5
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": true,
  "revId": 13,
  "applicationId": 9,
  "grantId": 5,
  "textField": "O candidato demonstra um grande dominio nas tecnologias."
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": true,
  "revId": 8,
  "applicationId": 9,
  "grantId": 5,
  "textField": "Um master em react era mesmo o que precisavamos."
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": false,
  "revId": 6,
  "applicationId": 10,
  "grantId": 5,
  "textField": "Apesar do grande dominio em Spring, também é necessario uma grande experiencia em react."
}

###
POST http://localhost:8080/eval
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKU09OIFdlYiBUb2tlbiBmb3IgQ0lBSSAyMDE5LzIwIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfU1RVREVOVCJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjA3MTM1OTg5LCJpYXQiOjE2MDcwOTk5ODksInVzZXJuYW1lIjoianBmLmZlcm5hbmRlcyJ9.edPllHxpjxJ0zE3wCEFEp-r_B_zuIZZhoGhO7fEnpbM

{
  "id": 0,
  "status": false,
  "revId": 7,
  "applicationId": 10,
  "grantId": 5,
  "textField": "Se não domina react não tem hipoteses"
}

